version: "3.8"
services:
    spark-master:
        image: spark-master
        ports:
            - 8080:8080
            - 7077:7077
    spark-worker:
        image: spark-worker
        depends_on:
            - spark-master
