version: "3.8"
services:
    spark-master:
        image: spark-master
        ports:
            - 8080:8080
            - 7077:7077
    spark-worker:
        image: spark-worker
        depends_on:
            - spark-master
    prometheus:
        image: prom/prometheus
        privileged: true
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
            - "9090:9090"
        depends_on:
            - cadvisor
    cadvisor:
        image: google/cadvisor
        ports:
            - "8080:8081"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"
