scrape_configs:
    - job_name: prometheus
      scrape_interval: 5s
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: cadvisor
      scrape_interval: 5s
      dns_sd_configs:
          - names: ["tasks.cadvisor"]
            type: "A"
            port: 8080
