version: "3.8"
services:
    spark-master:
        image: spark-master
        ports:
            - 4040:4040
            - 7077:7077
        networks:
            - computing
    spark-worker:
        image: spark-worker
        depends_on:
            - spark-master
        networks:
            - computing

networks:
    computing:
